# Generated by Django 2.1.5 on 2021-03-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_auto_20210327_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='chop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
