# Generated by Django 2.1.5 on 2021-03-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20210327_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(max_length=20),
        ),
    ]
