# Generated by Django 2.1.5 on 2021-03-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_auto_20210327_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='link',
        ),
    ]
