# Generated by Django 2.1.5 on 2021-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_remove_item_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='./static/image/items/default.png', upload_to='./static/image/items/upload/'),
        ),
    ]
