# Generated by Django 2.1.5 on 2021-03-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atc',
            options={'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.AlterModelOptions(
            name='atctype',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
