# Generated by Django 2.1.5 on 2021-03-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210317_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atc',
            options={'ordering': ['-create_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
