# Generated by Django 2.1.5 on 2021-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210320_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='atc',
            name='toc',
            field=models.TextField(default=''),
        ),
    ]
