# Generated by Django 2.1.5 on 2021-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_atc_toc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atc',
            name='toc',
            field=models.TextField(default=None),
        ),
    ]
