# Generated by Django 2.1.5 on 2021-03-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210325_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atc',
            name='toc',
            field=models.TextField(),
        ),
    ]
