# Generated by Django 2.1.5 on 2021-03-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_atc_toc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atc',
            options={'ordering': ['-create_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
