# Generated by Django 2.1.5 on 2021-03-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='./static/image/icon/default/male.jpg', upload_to='./static/image/icon/upload/'),
        ),
    ]
