# Generated by Django 2.1.5 on 2021-03-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='./static/image/icon/default/male.png', upload_to='./static/image/icon/upload/'),
        ),
    ]
