# Generated by Django 2.1.5 on 2021-03-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
